const http=require('http'); const fs=require('fs'); const path=require('path');
const D=path.join(__dirname,'data'); const sf=path.join(D,'sources.json'), lf=path.join(D,'listings.json');
const read=f=>JSON.parse(fs.readFileSync(f,'utf8')); const write=(f,v)=>fs.writeFileSync(f,JSON.stringify(v,null,2));
const norm=s=>(s||'').replace(/\u00a0/g,' ').replace(/\s+/g,' ').trim();
function num(s){if(!s)return null; let x=String(s).replace(/[^0-9,.-]/g,'').replace(/\.(?=\d{3}(?:\D|$))/g,'').replace(',','.'); let n=parseFloat(x); return Number.isFinite(n)?n:null}
function roomCount(t){t=norm(t).toLowerCase(); let m=t.match(/(\d+)\s*(?:camere|camera|dormitor)/); if(m)return +m[1]; if(/garsonier|studio/.test(t))return 1; return null}
function extractFromText(text, source, url){text=norm(text); let title=(text.match(/(?:Apartament|Garsonier|Studio|Duplex|Vila|Vilă)[^€]{0,90}/i)||[])[0]; if(!title)return null; let rooms=roomCount(title+' '+text); let priceM=text.match(/(?:de la\s*)?([0-9][0-9.\s]{3,}(?:,[0-9]+)?)\s*(?:€|EURO)/i); let price=priceM?num(priceM[1]):null; let areaM=text.match(/(?:Suprafa(?:ță|ta)(?:\s+utilă|\s+totală|\s+construită)?|Suprafață)\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)\s*m/i); let area=areaM?num(areaM[1]):null; let usefulM=text.match(/Suprafa(?:ță|ta)\s+utilă\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)\s*m/i); let totalM=text.match(/Suprafa(?:ță|ta)\s+totală\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)\s*m/i); let builtM=text.match(/Suprafa(?:ță|ta)\s+construită\s*[:\-]?\s*([0-9]+(?:[.,][0-9]+)?)\s*m/i);
 let useful=usefulM?num(usefulM[1]):area, total=totalM?num(totalM[1]):null, built=builtM?num(builtM[1]):null;
 let sold=/sold\s*out|vândut|vandut/i.test(text); let vat=/tva\s+inclus/i.test(text)?'included':(/\+\s*tva|nu includ[^.]{0,20}tva/i.test(text)?'excluded':'NA');
 let completion=(text.match(/(?:Finalizare|Finalizat|gata de mutare)[^.;]{0,40}/i)||[])[0]||'NA';
 let type=(title.match(/(?:tip|T)\s*[A-Z0-9.\-]+/i)||[])[0]||title;
 return {id:source.id+'-'+Buffer.from(url+'|'+type).toString('base64url').slice(0,18),sourceId:source.id,developer:source.name,project:source.name,type:norm(type),title:norm(title),rooms,price,vat,usefulArea:useful,totalArea:total,builtArea:built,pricePerSqm:price&&useful?Math.round(price/useful):null,status:sold?'sold':'available',completion:norm(completion),address:'NA',facilities:[],sourceUrl:url,lastChecked:new Date().toISOString()}; }
async function fetchHtml(url){let r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 AptCompareBot/1.0 (+price comparison prototype)','accept-language':'ro-RO,ro;q=0.9,en;q=0.7'},redirect:'follow'}); if(!r.ok)throw new Error('HTTP '+r.status); return await r.text();}
function sameHost(a,b){try{return new URL(a).hostname.replace(/^www\./,'')===new URL(b).hostname.replace(/^www\./,'')}catch{return false}}
function stripTags(s){return norm(String(s).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&euro;|&#8364;/gi,'€').replace(/&amp;/gi,'&'))}
function candidateLinks(html,base){let out=[],re=/<a\b[^>]*href=[\"']([^\"']+)[\"'][^>]*>([\s\S]*?)<\/a>/gi,m; while((m=re.exec(html))){try{let u=new URL(m[1],base).href.split('#')[0],tx=stripTags(m[2]).toLowerCase(); if(sameHost(u,base)&&/(apart|garson|studio|duplex|vila|vilă|2-cam|3-cam|4-cam|property|unit)/i.test(u+' '+tx)) out.push(u)}catch{}} return [...new Set(out)].slice(0,35)}
function blocks(html){let out=[],re=/<(?:article|li|div|section)\b[^>]*(?:class=[\"'][^\"']*(?:apart|property|unit|card|item|listing)[^\"']*[\"'])?[^>]*>([\s\S]{20,5000}?)<\/(?:article|li|div|section)>/gi,m; while((m=re.exec(html))){let t=stripTags(m[1]); if(t.length>25&&t.length<2500&&/(apartament|garsonier|studio|duplex|vila|vilă)/i.test(t))out.push(t)} if(!out.length){let text=stripTags(html); for(let part of text.split(/(?=Apartament|Garsonier|Studio|Duplex|Vila|Vilă)/i)){part=norm(part).slice(0,2200); if(part.length>25&&/(apartament|garsonier|studio|duplex|vila|vilă)/i.test(part))out.push(part)}} return [...new Set(out)]}
async function scanSource(source){let queue=[source.url], seen=new Set(), items=[]; while(queue.length&&seen.size<30){let url=queue.shift(); if(seen.has(url))continue; seen.add(url); try{let html=await fetchHtml(url); for(let t of blocks(html)){let x=extractFromText(t,source,url); if(x)items.push(x)} if(seen.size<8) for(let l of candidateLinks(html,url)) if(!seen.has(l)) queue.push(l)}catch(e){console.error(source.name,url,e.message)}}
 let uniq=new Map(); for(let x of items){let key=[x.sourceId,x.type,x.rooms,x.price,x.usefulArea,x.sourceUrl].join('|'); if(!uniq.has(key))uniq.set(key,x)} return [...uniq.values()];}
function json(res,status,obj){let b=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(b)});res.end(b)}
async function body(req){return await new Promise((resolve,reject)=>{let d='';req.on('data',c=>{d+=c;if(d.length>1e6)req.destroy()});req.on('end',()=>{try{resolve(d?JSON.parse(d):{})}catch(e){reject(e)}});req.on('error',reject)})}
function serve(res,file){try{let b=fs.readFileSync(file), ext=path.extname(file); let ct=ext==='.html'?'text/html; charset=utf-8':ext==='.css'?'text/css; charset=utf-8':ext==='.js'?'application/javascript; charset=utf-8':'application/octet-stream';res.writeHead(200,{'content-type':ct});res.end(b)}catch{res.writeHead(404);res.end('Not found')}}
const server=http.createServer(async(req,res)=>{let u=new URL(req.url,'http://localhost'); try{
 if(req.method==='GET'&&u.pathname==='/api/sources')return json(res,200,read(sf));
 if(req.method==='GET'&&u.pathname==='/api/listings')return json(res,200,read(lf));
 if(req.method==='GET'&&u.pathname==='/api/health')return json(res,200,{ok:true,sources:read(sf).length,listings:read(lf).length});
 if(req.method==='POST'&&u.pathname==='/api/sources'){let b=await body(req),a=read(sf),id=(b.name||'source').toLowerCase().replace(/[^a-z0-9]+/g,'-')+'-'+Date.now().toString(36),s={id,name:b.name||new URL(b.url).hostname,url:b.url,enabled:true};a.push(s);write(sf,a);return json(res,200,s)}
 let m=u.pathname.match(/^\/api\/scan\/([^/]+)$/); if(req.method==='POST'&&m){let s=read(sf).find(x=>x.id===m[1]);if(!s)return json(res,404,{error:'Sursa nu există'});let found=await scanSource(s),all=read(lf).filter(x=>x.sourceId!==s.id);write(lf,[...all,...found]);return json(res,200,{source:s.name,found:found.length,listings:found})}
 if(req.method==='POST'&&u.pathname==='/api/scan-all'){let all=[],report=[];for(let s of read(sf).filter(x=>x.enabled)){try{let found=await scanSource(s);all.push(...found);report.push({source:s.name,found:found.length})}catch(e){report.push({source:s.name,error:e.message})}}write(lf,all);return json(res,200,{total:all.length,report})}
 let file=u.pathname==='/'?path.join(__dirname,'public','index.html'):path.join(__dirname,'public',u.pathname.replace(/^\//,'')); if(!file.startsWith(path.join(__dirname,'public')))return serve(res,''); return serve(res,file);
 }catch(e){return json(res,500,{error:e.message})}});
const port=process.env.PORT||3000;server.listen(port,()=>console.log('AptCompare http://localhost:'+port));
